language: python

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
      - python3.6

install:
  - pip install tox
  - npm install -g bower

env:
  - TOXENV=py27-django18
  - TOXENV=py27-django111
  - TOXENV=py36-django18
  - TOXENV=py36-django19
  - TOXENV=py36-django110
  - TOXENV=py36-django111
  - TOXENV=py36-django_trunk
  - TOXENV=flake8

script:
  - tox

matrix:
  allow_failures:
    - env: TOXENV=py36-django_trunk
