language: python

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5

install:
  - pip install --upgrade pip setuptools tox virtualenv coveralls
  - npm install -g bower

env:
  - TOXENV=py27-django18
  - TOXENV=py27-django111
  - TOXENV=py35-django18
  - TOXENV=py35-django19
  - TOXENV=py35-django110
  - TOXENV=py35-django111
  - TOXENV=py35-django_trunk
  - TOXENV=flake8

script:
  - tox

matrix:
  allow_failures:
    - env: TOXENV=py35-django_trunk
